Added pyfiles and files argument
gdiepen/livy-submit pull request #3
Opened 2021-05-23 10:58 UTC by prabvija

1. Added py_files argument to pass python files using --py-files
2. Added files argument to pass config (such as yaml or json)
3. Added one additional argument to pass any external variable, to accept it in spark executor environment

2021-05-23 12:00 UTC, gdiepen requested changes
LGTM, just one remark regarding the print statement of the args

2021-05-23 12:00 UTC, gdiepen commented on livysubmit/livysubmit.py
> +    print(args)
If you can make this a logging debug statement instead a print statement, that would be better, since it technically is printing debug information and it is not application related output.

2021-05-23 12:38 UTC, prabvija commented on livysubmit/livysubmit.py
> +    print(args)
Removed the line as it only meant for debugging

2021-05-23 15:33 UTC, merged

2021-05-23 15:34 UTC, gdiepen commented
Thanks @prabvija

2021-05-23 18:48 UTC, prabvija commented
@gdiepen Can we also update these changes in pypi?

2021-05-23 18:49 UTC, gdiepen commented
Sure, will check tomorrow, some time ago that I did this

2021-05-24 09:02 UTC, gdiepen commented
@prabvija Done, should be a 1.1.0 version now